# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TaqbFX2Qv2hHeRw0nTzpMvQzvAyzUhq
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

# タイトル
st.title("データ分析ツール")

# 説明
st.write("""
エクセルやスプレッドシートからデータをコピーして以下の入力フォームに貼り付けてください。
X軸とY軸のデータがタブやカンマで区切られていれば自動的に処理します。
""")

# データ入力フォーム
input_data = st.text_area("データを入力してください（タブ区切りまたはカンマ区切り）", height=200)

if input_data:
    try:
        # 入力データの処理
        df = pd.read_csv(pd.compat.StringIO(input_data), sep=None, engine='python')

        # データが2列か確認
        if df.shape[1] != 2:
            st.error("2列のデータを入力してください（例: X, Y）。")
        else:
            # 列名の確認と修正
            df.columns = ["X", "Y"]

            # 数値変換
            df = df.astype(float)

            # 統計量の計算
            correlation = df["X"].corr(df["Y"])
            r_squared = r2_score(df["Y"], df["X"])
            stats = {
                "相関係数": correlation,
                "決定係数": r_squared,
                "Xの最大値": df["X"].max(),
                "Yの最大値": df["Y"].max(),
                "Xの最小値": df["X"].min(),
                "Yの最小値": df["Y"].min(),
                "Xの中央値": df["X"].median(),
                "Yの中央値": df["Y"].median(),
                "Xの平均": df["X"].mean(),
                "Yの平均": df["Y"].mean(),
            }

            # 結果の表示
            st.write("### 統計量の結果")
            st.json(stats)

            # 散布図の描画
            st.write("### 散布図")
            fig, ax = plt.subplots()
            ax.scatter(df["X"], df["Y"], color="blue", label="データポイント")
            ax.set_title("散布図")
            ax.set_xlabel("X軸")
            ax.set_ylabel("Y軸")
            ax.grid(True)
            ax.legend()
            st.pyplot(fig)

    except Exception as e:
        st.error(f"データの読み込み中にエラーが発生しました: {e}")